apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
data:
  telegram-bot-token: YOUR_BOT_TOKEN
type: Opaque

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.telegram: |
    token: $telegram-bot-token
    chatId: -4670849445

  context: |
    argocdUrl: http://argocd.sandbox.com:30080

  template.app-health-degraded: |
    message: |
      ⚠️ Application {{.app.metadata.name}} has degraded.
      Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}.

  template.app-sync-failed: |
    message: |
      ❌ The sync operation of application {{.app.metadata.name}} has failed at {{.app.status.operationState.finishedAt}} with the following error: {{.app.status.operationState.message}}
      Sync operation details are available at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true .

  template.app-sync-succeeded: |
    message: |
      ✅ Application {{.app.metadata.name}} has been successfully synced at {{.app.status.operationState.finishedAt}}.
      Sync operation details are available at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true .

  trigger.on-health-degraded: |
    - description: Application has degraded
      oncePer: app.status.health.status
      send: [app-health-degraded]
      when: app.status.health.status == 'Degraded'

  trigger.on-sync-failed: |
    - description: Application syncing has failed
      oncePer: app.status.operationState.operation.sync.revision
      send: [app-sync-failed]
      when: app.status.operationState.phase in ['Error', 'Failed']

  trigger.on-sync-succeeded: |
    - description: Application syncing has succeeded
      oncePer: app.status.sync.revision
      send: [app-sync-succeeded]
      when: app.status.operationState.phase in ['Succeeded']

  trigger.on-out-of-sync: |
    - description: Application is out of sync
      oncePer: app.status.sync.revision
      send: [app-out-of-sync]
      when: app.status.sync.status == 'OutOfSync'

  template.app-out-of-sync: |
    message: |
      ⚠️ Application {{.app.metadata.name}} is out of sync.
      Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}.
    