---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  finalizers:
    - argoproj.io/resources-finalizer
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.telegram: "-4670849445"
    notifications.argoproj.io/subscribe.on-sync-failed.telegram: "-4670849445"
    notifications.argoproj.io/subscribe.on-health-degraded.telegram: "-4670849445"
    notifications.argoproj.io/subscribe.on-sync-succeeded.telegram: "-4670849445"
    notifications.argoproj.io/subscribe.on-out-of-sync.telegram: "-4670849445"
spec:
  project: default
  source:
    repoURL: https://kyverno.github.io/kyverno/
    targetRevision: 3.5.0
    chart: kyverno
    helm:
      parameters:
        - name: policyReportsCleanup.enabled
          value: 'false'
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      enabled: true
    syncOptions:
      - Validate=false
      - PruneLast=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
  finalizers:
    - argoproj.io/resources-finalizer
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.telegram: "-4670849445"
    notifications.argoproj.io/subscribe.on-sync-failed.telegram: "-4670849445"
    notifications.argoproj.io/subscribe.on-health-degraded.telegram: "-4670849445"
    notifications.argoproj.io/subscribe.on-sync-succeeded.telegram: "-4670849445"
    notifications.argoproj.io/subscribe.on-out-of-sync.telegram: "-4670849445"
spec:
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://kyverno.github.io/kyverno/
    targetRevision: 3.5.0
    chart: kyverno-policies
    helm:
      parameters:
        - name: skipBackgroundRequests
          value: 'true'
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      enabled: true
    syncOptions:
      - Validate=false
      - PruneLast=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2